import { Equipment, Employee, MaintenanceRecord, CalibrationRecord, DocumentRecord } from '../types';
import { DEFAULT_COMPANY_ID } from './storage';
import { getDateOffsetString } from '../utils/dateUtils';

export function getInitialSeedData() {
  const now = new Date().toISOString();

  // 1. Equipment Seed Data
  const equipment: Equipment[] = [
    {
      id: 'eq_001_ut',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Mesureur d’épaisseur ultrasonique 38DL Plus',
      category: 'Contrôle Non Destructif (CND)',
      assetId: 'EQ-CND-001',
      codification: 'CND-US-38DL',
      manufacturer: 'Evident / Olympus',
      model: '38DL Plus High-Precision',
      serialNumber: '38DL-94821',
      location: 'Atelier Métrologie - Salle CND',
      process: 'Contrôle corrosion tuyauteries sous pression',
      availability: 'IN_SERVICE',
      lastCalibrationDate: getDateOffsetString(-380),
      nextCalibrationDate: getDateOffsetString(-15), // OVERDUE by 15 days
      validityPeriodMonths: 12,
      inspectionOrganization: 'Olympus Metrology Service',
      lastMaintenanceDate: getDateOffsetString(-90),
      nextMaintenanceDate: getDateOffsetString(60), // Due in 60 days
      lifeSheetRef: 'FDV-2023-CND-001',
      notes: 'Sonde standard D790-SM fournie. Utilisé pour les contrôles DESP.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'eq_002_lux',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Luxmètre numérique industriel',
      category: 'Optique & Éclairagisme',
      assetId: 'EQ-OPT-002',
      codification: 'OPT-LUX-540',
      manufacturer: 'Testo',
      model: 'Testo 540 PocketLine',
      serialNumber: 'T540-10924',
      location: 'Laboratoire Contrôle Qualité',
      process: 'Vérification de l’éclairement des cabines de ressuage CND (> 1000 lux)',
      availability: 'OUT_OF_SERVICE',
      lastCalibrationDate: getDateOffsetString(-407),
      nextCalibrationDate: getDateOffsetString(-42), // OVERDUE by 42 days
      validityPeriodMonths: 12,
      inspectionOrganization: 'Bureau Veritas Métrologie',
      lastMaintenanceDate: getDateOffsetString(-185),
      nextMaintenanceDate: getDateOffsetString(-5), // OVERDUE maintenance by 5 days
      lifeSheetRef: 'FDV-2022-OPT-002',
      notes: 'Capteur optique à réétalonner d’urgence avec filtre photopique V(λ).',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'eq_003_paut',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Détecteur de défauts Phased Array OmniScan X3',
      category: 'Contrôle Non Destructif (CND)',
      assetId: 'EQ-CND-003',
      codification: 'CND-PAUT-OX3',
      manufacturer: 'Evident / Olympus',
      model: 'OmniScan X3 64:128PR',
      serialNumber: 'OX3-44018',
      location: 'Véhicule d’intervention Mobile 01',
      process: 'Inspection soudures bout à bout & cartographie TFM',
      availability: 'IN_SERVICE',
      lastCalibrationDate: getDateOffsetString(-353),
      nextCalibrationDate: getDateOffsetString(12), // DUE IN 12 DAYS (<30d)
      validityPeriodMonths: 12,
      inspectionOrganization: 'Apave Metrology',
      lastMaintenanceDate: getDateOffsetString(-120),
      nextMaintenanceDate: getDateOffsetString(45),
      lifeSheetRef: 'FDV-2024-CND-003',
      notes: 'Module TFM actif. Calibrer avec cales étalons ISO 2400 et ISO 7963.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'eq_004_megger',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Mégohmmètre numérique 5 kV C.A 6545',
      category: 'Électricité & Isolement',
      assetId: 'EQ-ELEC-004',
      codification: 'ELEC-ISO-6545',
      manufacturer: 'Chauvin Arnoux',
      model: 'C.A 6545 Megohmmeter',
      serialNumber: 'CA65-88310',
      location: 'Atelier Maintenance Électrique',
      process: 'Mesure de résistance d’isolement sur transformateurs et moteurs HT',
      availability: 'IN_SERVICE',
      lastCalibrationDate: getDateOffsetString(-341),
      nextCalibrationDate: getDateOffsetString(24), // DUE IN 24 DAYS (<30d)
      validityPeriodMonths: 12,
      inspectionOrganization: 'CETIM Métrologie',
      lastMaintenanceDate: getDateOffsetString(-160),
      nextMaintenanceDate: getDateOffsetString(24),
      lifeSheetRef: 'FDV-2023-ELEC-004',
      notes: 'Cordon haute sécurité 5kV contrôlé. Tension d’essai jusqu’à 5000V DC.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'eq_005_calib',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Calibrateur de process documenté Fluke 754',
      category: 'Métrologie & Instrumentation',
      assetId: 'EQ-INST-005',
      codification: 'INST-CAL-754',
      manufacturer: 'Fluke Corporation',
      model: 'Fluke 754 HART Documenting Process Calibrator',
      serialNumber: 'F754-55912',
      location: 'Laboratoire Étalonnage Process',
      process: 'Étalonnage transmetteurs de pression, température et boucles 4-20 mA',
      availability: 'IN_SERVICE',
      lastCalibrationDate: getDateOffsetString(-310),
      nextCalibrationDate: getDateOffsetString(55), // DUE IN 55 DAYS (<90d)
      validityPeriodMonths: 12,
      inspectionOrganization: 'Fluke Metrology Services Europe',
      lastMaintenanceDate: getDateOffsetString(-150),
      nextMaintenanceDate: getDateOffsetString(120),
      lifeSheetRef: 'FDV-2023-INST-005',
      notes: 'Fourni avec module de pression Fluke 700P07 (7 bar). Certificat COFRAC requis.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'eq_006_temp',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Puits de température d’étalonnage Fluke 9142',
      category: 'Métrologie & Instrumentation',
      assetId: 'EQ-INST-006',
      codification: 'INST-TEMP-9142',
      manufacturer: 'Fluke Calibration',
      model: '9142 Field Dry-Well Calibrator (-25°C à 150°C)',
      serialNumber: 'FC91-31409',
      location: 'Laboratoire Étalonnage Process',
      process: 'Vérification des sondes PT100 et thermocouples agro/chimie',
      availability: 'IN_SERVICE',
      lastCalibrationDate: getDateOffsetString(-287),
      nextCalibrationDate: getDateOffsetString(78), // DUE IN 78 DAYS (<90d)
      validityPeriodMonths: 12,
      inspectionOrganization: 'Trescal France',
      lastMaintenanceDate: getDateOffsetString(-100),
      nextMaintenanceDate: getDateOffsetString(180),
      lifeSheetRef: 'FDV-2023-INST-006',
      notes: 'Puits en aluminium avec insert multi-trous 1/4" et 3/16". Stabilité ±0.01°C.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'eq_007_multimeter',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Multimètre numérique True-RMS Fluke 87V MAX',
      category: 'Électricité & Mesure',
      assetId: 'EQ-ELEC-007',
      codification: 'ELEC-MULT-87V',
      manufacturer: 'Fluke Corporation',
      model: 'Fluke 87V MAX Industrial Multimeter',
      serialNumber: 'F87V-99231',
      location: 'Magasin Central - Valise Outillage C1',
      process: 'Mesures électriques en environnements sévères IP67',
      availability: 'IN_SERVICE',
      lastCalibrationDate: getDateOffsetString(-185),
      nextCalibrationDate: getDateOffsetString(180), // VALID (180 days)
      validityPeriodMonths: 12,
      inspectionOrganization: 'Fluke Metrology Services Europe',
      lastMaintenanceDate: getDateOffsetString(-185),
      nextMaintenanceDate: getDateOffsetString(180),
      lifeSheetRef: 'FDV-2024-ELEC-007',
      notes: 'Batterie 9V et fusibles 11A neufs. Conforme CAT III 1000V / CAT IV 600V.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'eq_008_clamp',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Pince multimètre True-RMS AC/DC Fluke 376 FC',
      category: 'Électricité & Mesure',
      assetId: 'EQ-ELEC-008',
      codification: 'ELEC-PINC-376',
      manufacturer: 'Fluke Corporation',
      model: 'Fluke 376 FC avec sonde souple iFlex',
      serialNumber: 'F376-77124',
      location: 'Magasin Central - Valise Outillage C2',
      process: 'Mesure de courant moteur jusqu’à 2500A AC et 1000A DC',
      availability: 'IN_SERVICE',
      lastCalibrationDate: getDateOffsetString(-125),
      nextCalibrationDate: getDateOffsetString(240), // VALID (240 days)
      validityPeriodMonths: 12,
      inspectionOrganization: 'CETIM Métrologie',
      lastMaintenanceDate: getDateOffsetString(-125),
      nextMaintenanceDate: getDateOffsetString(240),
      lifeSheetRef: 'FDV-2024-ELEC-008',
      notes: 'Sonde iFlex 45 cm vérifiée et testée diélectrique.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'eq_009_yoke',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Électro-aimant articulé de magnétoscopie Y-7',
      category: 'Contrôle Non Destructif (CND)',
      assetId: 'EQ-CND-009',
      codification: 'CND-MAG-Y7',
      manufacturer: 'Magnaflux',
      model: 'Y-7 AC/DC Magnetic Particle Yoke',
      serialNumber: 'MY7-33100',
      location: 'Atelier CND - Zone Magnéto',
      process: 'Détection de fissures débouchantes sur cordons de soudure ferro-magnétiques',
      availability: 'IN_SERVICE',
      lastCalibrationDate: getDateOffsetString(-45),
      nextCalibrationDate: getDateOffsetString(320), // VALID (320 days)
      validityPeriodMonths: 12,
      inspectionOrganization: 'Bureau Veritas Exploitation',
      lastMaintenanceDate: getDateOffsetString(-45),
      nextMaintenanceDate: getDateOffsetString(135),
      lifeSheetRef: 'FDV-2024-CND-009',
      notes: 'Force d’arrachement validée à 4.5 kg en AC et 18 kg en DC avec masse étalon.',
      createdAt: now,
      updatedAt: now,
    },
  ];

  // 2. Employees Seed Data
  const employees: Employee[] = [
    {
      id: 'emp_001',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Jean-Pierre Laurent',
      employeeId: 'MAT-2018-042',
      position: 'Inspecteur CND Senior & Spécialiste Ultrasons',
      department: 'Pôle Contrôle Non Destructif',
      certificateName: 'COFREND Ultrasons (UT) Niveau 2 - EN ISO 9712',
      certificateNumber: 'COF-UT2-884129',
      issueDate: getDateOffsetString(-1843), // 5 years ago
      expiryDate: getDateOffsetString(-18),  // OVERDUE by 18 days
      notes: 'Dossier de renouvellement quinquennal soumis à la COFREND. En attente de commission.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'emp_002',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Sophie Marchand',
      employeeId: 'MAT-2020-019',
      position: 'Technicienne d’Étalonnage & Métrologue',
      department: 'Laboratoire Métrologie',
      certificateName: 'Habilitation Électrique B2V / BC / H0V (NF C 18-510)',
      certificateNumber: 'HAB-ELEC-2023-019',
      issueDate: getDateOffsetString(-1081),
      expiryDate: getDateOffsetString(14),   // DUE IN 14 DAYS (<30d)
      notes: 'Recyclage planifié auprès de l’APAVE la semaine prochaine.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'emp_003',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Alexandre Dumas',
      employeeId: 'MAT-2021-067',
      position: 'Contrôleur Qualité & CND Polyvalent',
      department: 'Pôle Contrôle Non Destructif',
      certificateName: 'COFREND Magnétoscopie (MT) Niveau 2 - EN ISO 9712',
      certificateNumber: 'COF-MT2-990314',
      issueDate: getDateOffsetString(-1760),
      expiryDate: getDateOffsetString(62),   // DUE IN 62 DAYS (<90d)
      notes: 'Session d’examen pratique de recertification réservée pour le mois prochain.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'emp_004',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Élodie Bernard',
      employeeId: 'MAT-2019-005',
      position: 'Responsable Qualité & Métrologie Légale',
      department: 'Direction Qualité & Conformité',
      certificateName: 'Auditeur Qualité Laboratoire ISO/IEC 17025 (COFRAC)',
      certificateNumber: 'AUD-17025-FR-441',
      issueDate: getDateOffsetString(-440),
      expiryDate: getDateOffsetString(290),  // VALID (290 days)
      notes: 'Certifiée AFNOR Compétences. Pilote des audits d’accréditation COFRAC.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'emp_005',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Marc Vasseur',
      employeeId: 'MAT-2022-088',
      position: 'Technicien de Maintenance Électromécanique',
      department: 'Atelier Maintenance',
      certificateName: 'Contrôleur Équipements Sous Pression (DESP 2014/68/UE)',
      certificateNumber: 'DESP-ESP-2023-88',
      issueDate: getDateOffsetString(-200),
      expiryDate: getDateOffsetString(365),  // VALID (1 year)
      notes: 'Habilité aux inspections périodiques des générateurs de vapeur et récipients à pression.',
      createdAt: now,
      updatedAt: now,
    },
  ];

  // 3. Maintenance Records Seed Data
  const maintenance: MaintenanceRecord[] = [
    {
      id: 'maint_001',
      equipmentId: 'eq_001_ut',
      companyId: DEFAULT_COMPANY_ID,
      date: getDateOffsetString(-90),
      type: 'PREVENTIVE',
      description: 'Remplacement du pack batterie Li-ion, nettoyage des connecteurs LEMO 00 et vérification des câbles de sonde.',
      technician: 'Maintenance Guardian Tech Service / Luc Moreau',
      cost: 380,
      nextMaintenanceDate: getDateOffsetString(60),
      notes: 'Test de continuité OK. Pas d’oxydation sur les broches.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'maint_002',
      equipmentId: 'eq_002_lux',
      companyId: DEFAULT_COMPANY_ID,
      date: getDateOffsetString(-185),
      type: 'CORRECTIVE',
      description: 'Remplacement de la cellule silicium suite à un choc mécanique en atelier.',
      technician: 'Testo SAV France',
      cost: 215,
      nextMaintenanceDate: getDateOffsetString(-5),
      notes: 'Attente du nouvel étalonnage avant remise en service.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'maint_003',
      equipmentId: 'eq_003_paut',
      companyId: DEFAULT_COMPANY_ID,
      date: getDateOffsetString(-120),
      type: 'PREVENTIVE',
      description: 'Dépoussiérage ventilation interne, mise à jour firmware MXU 5.4, calibration de l’écran tactile.',
      technician: 'Evident Service Center',
      cost: 920,
      nextMaintenanceDate: getDateOffsetString(45),
      notes: 'Rapport d’intervention constructeur joint.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'maint_004',
      equipmentId: 'eq_004_megger',
      companyId: DEFAULT_COMPANY_ID,
      date: getDateOffsetString(-160),
      type: 'INSPECTION',
      description: 'Vérification de sécurité électrique, contrôle des cordons haute tension et du commutateur rotatif.',
      technician: 'Atelier Central Électromécanique',
      cost: 150,
      nextMaintenanceDate: getDateOffsetString(24),
      notes: 'Isolement des cordons testé à 10 kV.',
      createdAt: now,
      updatedAt: now,
    },
  ];

  // 4. Calibration Records Seed Data
  const calibrations: CalibrationRecord[] = [
    {
      id: 'cal_001',
      equipmentId: 'eq_001_ut',
      companyId: DEFAULT_COMPANY_ID,
      date: getDateOffsetString(-380),
      type: 'EXTERNAL_CALIBRATION',
      result: 'CONFORM',
      certificateNumber: 'CERT-OLY-2023-9941',
      performedBy: 'Olympus Metrology Service',
      nextDueDate: getDateOffsetString(-15), // OVERDUE
      notes: 'Étalonnage d’épaisseur vérifié sur cales étalons 1 mm à 100 mm en acier carbone.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cal_002',
      equipmentId: 'eq_002_lux',
      companyId: DEFAULT_COMPANY_ID,
      date: getDateOffsetString(-407),
      type: 'PERIODIC_INSPECTION',
      result: 'RESTRICTED',
      certificateNumber: 'PV-BV-2023-4410',
      performedBy: 'Bureau Veritas Métrologie',
      nextDueDate: getDateOffsetString(-42), // OVERDUE
      notes: 'Dérive de +4% détectée sur la plage 0-500 lux. Restriction d’usage aux plages > 1000 lux.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cal_003',
      equipmentId: 'eq_003_paut',
      companyId: DEFAULT_COMPANY_ID,
      date: getDateOffsetString(-353),
      type: 'EXTERNAL_CALIBRATION',
      result: 'CONFORM',
      certificateNumber: 'CERT-APAVE-2023-PAUT',
      performedBy: 'Apave Metrology Services',
      nextDueDate: getDateOffsetString(12), // DUE IN 12 DAYS
      notes: 'Vérification linéarité des voies 64:128 et retard d’angle conforme NF EN 12668-1.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cal_004',
      equipmentId: 'eq_004_megger',
      companyId: DEFAULT_COMPANY_ID,
      date: getDateOffsetString(-341),
      type: 'EXTERNAL_CALIBRATION',
      result: 'CONFORM',
      certificateNumber: 'CETIM-CAL-2023-ELEC',
      performedBy: 'CETIM Métrologie Électrique',
      nextDueDate: getDateOffsetString(24), // DUE IN 24 DAYS
      notes: 'Incertitude de mesure U = 1.2% sous 5000V. Validé pour les audits d’installation.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cal_005',
      equipmentId: 'eq_005_calib',
      companyId: DEFAULT_COMPANY_ID,
      date: getDateOffsetString(-310),
      type: 'LEGAL_METROLOGY',
      result: 'CONFORM',
      certificateNumber: 'COFRAC-FLUKE-754-098',
      performedBy: 'Fluke European Metrology Lab',
      nextDueDate: getDateOffsetString(55), // DUE IN 55 DAYS
      notes: 'Raccordement aux étalons nationaux LNE/NIST. Certificat d’étalonnage officiel COFRAC.',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cal_006',
      equipmentId: 'eq_006_temp',
      companyId: DEFAULT_COMPANY_ID,
      date: getDateOffsetString(-287),
      type: 'EXTERNAL_CALIBRATION',
      result: 'CONFORM',
      certificateNumber: 'TRESCAL-TEMP-9142-88',
      performedBy: 'Trescal Calibration Services',
      nextDueDate: getDateOffsetString(78), // DUE IN 78 DAYS
      notes: 'Profil de température relevé à -20°C, 0°C, 50°C, 100°C et 150°C. Axial gradient < 0.05°C.',
      createdAt: now,
      updatedAt: now,
    },
  ];

  // 5. Document Records Seed Data
  const documents: DocumentRecord[] = [
    {
      id: 'doc_001',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Certificat d’Étalonnage COFRAC Olympus 38DL Plus',
      type: 'CALIBRATION_CERTIFICATE',
      referenceNumber: 'CERT-OLY-2023-9941',
      date: getDateOffsetString(-380),
      associatedType: 'EQUIPMENT',
      associatedId: 'eq_001_ut',
      associatedName: 'Mesureur d’épaisseur ultrasonique 38DL Plus',
      fileName: 'Certificat_Etalonnage_38DLPlus_2023.pdf',
      fileSize: '1.8 MB',
      notes: 'Certificat de conformité métrologique initial.',
      createdAt: now,
    },
    {
      id: 'doc_002',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Rapport de Contrôle Périodique OmniScan X3',
      type: 'CALIBRATION_CERTIFICATE',
      referenceNumber: 'CERT-APAVE-2023-PAUT',
      date: getDateOffsetString(-353),
      associatedType: 'EQUIPMENT',
      associatedId: 'eq_003_paut',
      associatedName: 'Détecteur de défauts Phased Array OmniScan X3',
      fileName: 'PV_Controle_Apave_OmniScanX3.pdf',
      fileSize: '3.2 MB',
      notes: 'Rapport complet avec courbes de linéarité amplitude et base de temps.',
      createdAt: now,
    },
    {
      id: 'doc_003',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Manuel Utilisateur & Spécifications C.A 6545',
      type: 'USER_MANUAL',
      referenceNumber: 'MAN-CA-6545-REV3',
      date: getDateOffsetString(-500),
      associatedType: 'EQUIPMENT',
      associatedId: 'eq_004_megger',
      associatedName: 'Mégohmmètre numérique 5 kV C.A 6545',
      fileName: 'Manuel_Utilisation_CA6545.pdf',
      fileSize: '4.5 MB',
      notes: 'Notice officielle constructeur Chauvin Arnoux.',
      createdAt: now,
    },
    {
      id: 'doc_004',
      companyId: DEFAULT_COMPANY_ID,
      name: 'Certificat COFREND UT Niveau 2 - J.P. Laurent',
      type: 'EMPLOYEE_CERTIFICATE',
      referenceNumber: 'COF-UT2-884129',
      date: getDateOffsetString(-1843),
      associatedType: 'EMPLOYEE',
      associatedId: 'emp_001',
      associatedName: 'Jean-Pierre Laurent',
      fileName: 'Certificat_COFREND_UT2_JP_Laurent.pdf',
      fileSize: '840 KB',
      notes: 'Attestation originale de qualification sectorielle.',
      createdAt: now,
    },
  ];

  return {
    equipment,
    employees,
    maintenance,
    calibrations,
    documents,
  };
}
